os: linux

language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

install:
  - pip install -r requirements.txt

services:
  - docker


scripts:
  - python -m unittest discover

branches:
  only:
    - master
    -