os: linux

language: python

python:
  - 3.7
  - 3.8
  - 3.9

install:
  - pip install -r requirements-dev.txt

services:
  - docker

before_script:
  - docker-compose up -d
  - docker-compose ps

scripts:
  - python -m unittest discover


after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker images
  - docker tag advancedpython_homework3_app:latest $DOCKER_USERNAME/advancedpython_hw3_api:travis
  - docker tag advancedpython_homework3_worker:latest $DOCKER_USERNAME/advancedpythonhw3_worker:travis
  - docker push $DOCKER_USERNAME/advancedpython_hw3_api:travis
  - docker push $DOCKER_USERNAME/advancedpythonhw3_worker:travis

branches:
  only:
    - master