version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask
    restart: always
    volumes:
      - logs:/logs
    links:
      - mongo
    ports:
      - "5000:5000"
    depends_on:
      - redis
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: ./models/db
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    volumes:
      - logs:/logs
    depends_on:
      - redis
  redis:
    image: redis
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  logs:

