version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask
    restart: always
    volumes:
      - logs:/logs
    ports:
      - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker
    volumes:
      - logs:/logs
      - models:/models
    depends_on:
      - redis
  redis:
    image: redis
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    links:
      - prometheus
  mlflow:
    container_name: tracker_mlflow
    restart: always
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - models:/models
    links:
      - worker
    entrypoint: mlflow server --backend-store-uri sqlite:///:database --default-artifact-root /models/ -h 0.0.0.0 -p 5050
volumes:
  logs:
  models:


